import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, Check, ChevronRight, Code2, Compass, Cpu, GraduationCap, Lightbulb, School, Sparkles, Wrench } from "lucide-react";
import { ProjectCard } from "@/components/project-card";
import { projects } from "@/lib/sample-data";
import { courses } from "@/lib/courses";
import "./home-design.css";

const fields = [
  { name: "Robotics & electronics", note: "Make things that sense, move and respond.", icon: Cpu, image: "/images/solar-rover-studio.webp", href: "/projects/solar-rover", number: "01" },
  { name: "Software & computer science", note: "Turn a useful idea into a working product.", icon: Code2, image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=900&q=85", href: "/projects/attendance-app", number: "02" },
  { name: "Energy & the built world", note: "Design for people, places and a changing planet.", icon: Lightbulb, image: "/images/schools-hero.webp", href: "/projects/portable-solar-charger", number: "03" },
];

export default function Home() {
  const featured = projects.find(item => item.slug === "solar-rover")!;
  return <main className="home-page">
    <section className="home-hero"><div className="container home-hero-grid"><div className="home-hero-copy">
      <div className="home-overline"><span className="home-overline-icon"><Sparkles size={14}/></span> THE FUTURE IS BUILT HERE</div>
      <h1>Curiosity is just<br/>the <em>beginning<span>.</span></em></h1>
      <p className="home-hero-lead">Learn engineering and computer science by building real things. Find a challenge, develop your skills and turn your ideas into something you can show the world.</p>
      <div className="home-hero-actions"><Link className="button" href="/projects">Explore projects <ArrowUpRight size={18}/></Link><Link className="home-quiet-link" href="/studio">Enter your studio <ArrowRight size={16}/></Link></div>
      <div className="home-levels"><span>BUILT FOR EVERY STAGE</span><div><Link href="/projects">JHS</Link><Link href="/projects">SHS</Link><Link href="/projects">University</Link></div></div>
    </div><div className="home-hero-visual"><div className="home-hero-photo" role="img" aria-label="Students building a solar-powered rover in a workshop"/><div className="home-photo-topline"><span className="home-live-dot"/> IDEAS INTO ACTION</div><Link className="home-hero-project" href="/projects/solar-rover"><span className="home-hero-project-icon"><Wrench size={22}/></span><span><small>PROJECT SPOTLIGHT</small><strong>Build a solar powered rover</strong><span>Explore the build brief <ArrowRight size={13}/></span></span><ArrowUpRight className="home-project-corner" size={18}/></Link></div></div><div className="home-hero-edge" aria-hidden="true">✳</div></section>

    <section className="home-promise"><div className="container home-promise-grid"><p>Big ideas need a place<br/><strong>to become real.</strong></p><div><span>01 <b>FIND YOUR SPARK</b></span><span>02 <b>LEARN BY MAKING</b></span><span>03 <b>SHOW YOUR WORK</b></span></div></div></section>

    <section className="container home-section home-fields"><div className="home-section-heading"><div><span className="home-kicker">EXPLORE THE POSSIBILITIES</span><h2>There&apos;s more than one<br/>way to <em>build the future.</em></h2><p>From circuits and code to cleaner energy and stronger communities, discover the field that pulls you in.</p></div><Link href="/projects" className="home-section-link">Browse all projects <ArrowUpRight size={17}/></Link></div><div className="home-field-grid">{fields.map(({ name, note, icon: Icon, image, href, number }) => <Link className="home-field-card" href={href} key={name}><div className="home-field-photo" style={{ backgroundImage: `url('${image}')` }}/><div className="home-field-overlay"/><div className="home-field-content"><span className="home-field-top"><span><Icon size={19}/></span><small>{number} / EXPLORE</small></span><div><h3>{name}</h3><p>{note}</p><span className="home-field-cta">Explore this field <ArrowUpRight size={16}/></span></div></div></Link>)}</div></section>

    <section className="home-feature-wrap"><div className="container home-feature"><div className="home-feature-image"><div role="img" aria-label="Solar rover prototype"/><span className="home-image-label">FEATURED PROJECT / ROBOTICS</span></div><div className="home-feature-copy"><span className="home-kicker">A PROJECT WORTH BUILDING</span><h2>Start with a problem.<br/><em>Build what&apos;s next.</em></h2><p>Design a rover that moves over rough ground and gathers environmental readings. Learn power budgeting, motor control and field testing as you make it your own.</p><div className="home-feature-facts"><span><b>{featured.level}</b><small>Learning level</small></span><span><b>{featured.duration}</b><small>Build timeline</small></span><span><b>{featured.type}</b><small>Project format</small></span></div><Link className="button" href={`/projects/${featured.slug}`}>Explore the project <ArrowRight size={17}/></Link></div></div></section>

    <section className="container home-section home-projects"><div className="home-section-heading compact"><div><span className="home-kicker">MADE FOR CURIOUS MINDS</span><h2>Find your next challenge.</h2><p>Start small or take on something ambitious. Every project begins with a question worth exploring.</p></div><Link className="home-section-link" href="/projects">All projects <ArrowUpRight size={17}/></Link></div><div className="home-project-grid">{["smart-irrigation", "attendance-app", "air-quality", "line-robot"].map(slug => { const project = projects.find(item => item.slug === slug)!; return <ProjectCard key={slug} project={project}/>; })}</div></section>

    <section className="home-journey"><div className="container home-journey-inner"><div className="home-journey-title"><span className="home-kicker">HOW BUILDLAB WORKS</span><h2>Make learning<br/><em>something you do.</em></h2><p>Explore the idea, learn the foundations and capture every step from first sketch to final test.</p><Link href="/courses" className="home-section-link">Explore course previews <ArrowRight size={16}/></Link></div><div className="home-journey-steps"><div><span className="journey-icon blue"><Compass size={23}/></span><small>01 / DISCOVER</small><h3>Choose your challenge.</h3><p>Browse project briefs shaped around real needs and pick one that sparks your curiosity.</p><Link href="/projects">Explore projects <ArrowRight size={13}/></Link></div><div><span className="journey-icon peach"><BookOpen size={23}/></span><small>02 / LEARN</small><h3>Build your foundations.</h3><p>Preview topics in electronics, energy, coding and design, then put them to work.</p><Link href="/courses">Browse courses <ArrowRight size={13}/></Link></div><div><span className="journey-icon green"><Wrench size={23}/></span><small>03 / MAKE</small><h3>Show how you built it.</h3><p>Use your studio to plan milestones, record trials and see how your project develops.</p><Link href="/studio">Open your studio <ArrowRight size={13}/></Link></div></div></div></section>

    <section className="container home-section home-studio"><div className="home-studio-copy"><span className="home-kicker">MEET YOUR STUDIO</span><h2>Every builder needs<br/>a place to <em>think bigger.</em></h2><p>Keep your projects moving with a personal workspace for plans, milestones and build notes. What you learn along the way is part of the story.</p><ul><li><Check size={16}/> Save and organize your projects</li><li><Check size={16}/> Track milestones as you build</li><li><Check size={16}/> Record experiments and changes</li></ul><Link className="button" href="/studio">Explore the studio <ArrowRight size={17}/></Link></div><div className="home-studio-preview" aria-label="Illustration of a BuildLab project workspace"><div className="home-preview-sidebar"><strong>◆ <span>BuildLab</span></strong><span className="selected">◫</span><span>▦</span><span>⌘</span><span>◉</span></div><div className="home-preview-main"><div className="home-preview-top"><span>YOUR STUDIO <ChevronRight size={11}/> PROJECTS</span><span>✦</span></div><div className="home-preview-heading"><small>PROJECT WORKSPACE</small><strong>Solar powered rover<span>.</span></strong><p>From an idea to a working prototype.</p></div><div className="home-preview-image"><div/><span>KEEP BUILDING <ArrowUpRight size={14}/></span></div><div className="home-preview-panels"><div><small>YOUR ROADMAP</small><span><i/> Research & design</span><span><i/> Prototype the system</span><span><i/> Test & improve</span></div><div><small>BUILD LOG</small><p>Capture what you tried, what worked and what comes next.</p><span className="home-preview-note">+ Add a note</span></div></div></div><span className="home-preview-tag">STUDIO PREVIEW</span></div></section>

    <section className="home-schools"><div className="container home-schools-grid"><div className="home-schools-photo" role="img" aria-label="Students collaborating in an engineering classroom"/><div className="home-schools-copy"><span className="home-kicker">FOR SCHOOLS & EDUCATORS</span><h2>Turn your classroom into a place where ideas take shape.</h2><p>Assign meaningful projects, give learners space to document their work and follow their progress from first idea to finished prototype.</p><div className="home-schools-points"><span><School size={17}/> Classes and assignments</span><span><GraduationCap size={17}/> Student project studios</span><span><Check size={17}/> Teacher progress view</span></div><Link className="button" href="/schools">Explore BuildLab for schools <ArrowRight size={17}/></Link></div></div></section>

    <section className="container home-section home-course-section"><div className="home-section-heading compact"><div><span className="home-kicker">LEARN THE FOUNDATION</span><h2>New skills, real possibilities.</h2><p>Preview the topics behind your next great build.</p></div><Link className="home-section-link" href="/courses">Explore courses <ArrowUpRight size={17}/></Link></div><div className="home-course-grid">{courses.slice(0, 3).map((course, i) => <Link href={`/courses/${course.slug}`} className="home-course-card" key={course.slug}><div className="home-course-image" style={{ backgroundImage: `url('${course.image}')` }}/><div><span>0{i + 1} / {course.field.toUpperCase()}</span><h3>{course.title}</h3><p>{course.description}</p><small>Free topic preview <ArrowUpRight size={15}/></small></div></Link>)}</div></section>

    <section className="home-end"><div className="container home-end-inner"><div className="home-end-spark">✳</div><span className="home-kicker">IDEAS BECOME REAL HERE</span><h2>What will you build?</h2><p>Pick a project, start with what you have and see where your curiosity takes you.</p><Link className="button" href="/projects">Find your first project <ArrowRight size={17}/></Link></div></section>
  </main>;
}
