import Link from "next/link";
import { ArrowRight, Check, Clock3, Layers3, Wrench } from "lucide-react";
import type { CatalogCourse, CatalogProject } from "@/lib/catalog";

export function CatalogProjectDetail({ project }: { project: CatalogProject }) {
  return <main className="project-detail-page">
    <div className="container project-breadcrumb"><Link href="/projects">Projects</Link><span> / </span><span>{project.category.name}</span><span> / </span><span>{project.title}</span></div>
    <section className="container project-detail-hero"><div className="project-detail-copy"><span className="eyebrow">THE BUILD BRIEF / {project.category.name.toUpperCase()}</span><div className="project-detail-tags"><span>{project.level}</span><span>{project.format} build</span></div><h1>{project.title}<span className="orange-dot">.</span></h1><p className="project-detail-intro">{project.summary}</p><div className="project-detail-actions"><Link className="button" href="/studio/new">Start a project <ArrowRight size={17}/></Link><a href="#overview">Read the brief ↓</a></div></div><div className="project-hero-visual"><div className="project-hero-photo" role="img" aria-label={project.title} style={{ backgroundImage: `url('${project.image_url || "/images/explore-hero.webp"}')` }}/></div></section>
    <div className="project-facts-wrap"><div className="container project-facts"><div><Clock3/><span><small>ESTIMATED TIME</small><strong>{project.duration}</strong></span></div><div><Layers3/><span><small>LEVEL</small><strong>{project.level}</strong></span></div><div><Wrench/><span><small>FORMAT</small><strong>{project.format}</strong></span></div><div><Check/><span><small>FIELD</small><strong>{project.category.name}</strong></span></div></div></div>
    <div className="container project-detail-body"><article className="project-content"><section id="overview" className="project-detail-section"><span className="project-section-kicker">01 / PROJECT OVERVIEW</span><h2>Take on the challenge.</h2>{project.description.split(/\n\s*\n/).map((paragraph, i) => <p key={i}>{paragraph}</p>)}</section></article><aside className="project-detail-aside"><div className="project-brief-card"><span className="eyebrow">BUILD WITH BUILDLAB</span><h3>Bring your idea to life.</h3><p>Create a workspace to plan milestones and document your experiments.</p><Link className="button" href="/studio/new">Open your studio <ArrowRight size={16}/></Link></div></aside></div>
  </main>;
}

export function CatalogCourseDetail({ course }: { course: CatalogCourse }) {
  return <main className="container course-detail"><Link className="back-link" href="/courses">← All courses</Link><div className="course-detail-hero"><div><span className="eyebrow">{course.category.name.toUpperCase()} · {course.level.toUpperCase()}</span><h1>{course.title}<span className="orange-dot">.</span></h1><p>{course.summary}</p><div className="detail-facts"><span>{course.lessons.length} topics</span><span>{course.hours} hours</span></div><a className="button" href="#lessons">Explore the topics ↓</a></div><div role="img" aria-label={course.title} style={{ backgroundImage: `url('${course.image_url || "/images/courses-hero.webp"}')` }}/></div><section id="lessons" className="course-lessons"><div><span className="eyebrow">YOUR LEARNING PATH</span><h2>Skills for a real build.</h2>{course.description.split(/\n\s*\n/).map((paragraph, i) => <p key={i}>{paragraph}</p>)}<Link className="text-link" href="/projects">Explore related projects →</Link></div><ol>{course.lessons.map((lesson, index) => <li key={lesson.id}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{lesson.title}</h3><p>{lesson.summary}</p></div></li>)}</ol></section></main>;
}
