source "https://rubygems.org"

gem "rails", "~> 7.2"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "rack-cors"
gem "bcrypt", "~> 3.1"
gem "bootsnap", require: false

group :development, :test do
  gem "debug"
end
